### ISSUE TITLE
Please release Spectron 14, compatible with electron 12

### ISSUE THREAD

**Issue by MatthijsBurgh** [electron-userland/spectron#883] opened 2021-03-03 13:59 UTC
I don't think any changes are needed except bumping the version number and updating the electron dependency.

**Comment by VerteDinde** [comment] 2021-03-03 20:39
Hey @MatthijsBurgh! Because we deprecated the remote module and turned on contextIsolation by default in Electron 12, we have to give Spectron a little extra love before we update it this time. 🙂 Apologies for the delay, but thanks for understanding! A new version, 14.0.0, should be published shortly.

**Comment by jtoy** [comment] 2021-03-04 20:08
+1

**Comment by Himani33** [comment] 2021-03-08 19:37
+1

**Comment by MatthijsBurgh** [comment] 2021-03-10 10:31
@VerteDinde I see you have merged #884. Thanks for that already. Is there anything holding a release to npm?

P.S. you might want to update the README to include the new version.

**Comment by VerteDinde** [comment] 2021-03-10 19:20
@MatthijsBurgh Sorry, looks like our publishing script didn't take the first time - I just published 14.0.0 to NPM, so it should be available for download now.

Thanks so much for your patience, all! I'm going to close this issue now that we have a published version confirmed, but if you have any issues with 14.0.0, please let us know. 

(As a small heads up: the remote module was deprecated in Electron 12, but in Electron 14, the built-it remote module will be removed entirely. If you're still using it in your apps, I would strongly encourage you to migrate toward using contextBridge instead as soon as you can.)

**Closed by VerteDinde** 2021-03-10 19:20 UTC
